export type ExactElement = {
  id: string;
  type: 'year-big' | 'year-small' | 'title' | 'body' | 'rule' | 'image' | 'today' | 'afford';
  x: number;
  y: number;
  w?: number;
  h?: number;
  html?: string;
  src?: string;
  alt?: string;
  isGreen?: boolean;
  zIndex?: number;
};

export type MilestoneExactSection = {
  id: string;
  title: string;
  yStart: number;
  height: number;
  elements: ExactElement[];
};

export const ARTBOARD_W = 913;

export const MILESTONES_EXACT: MilestoneExactSection[] = [
  // 1940s
  {
    id: '1940s',
    title: '1940s — The Beginning',
    yStart: 0,
    height: 760,
    elements: [
      {
        id: '1940-year',
        type: 'year-big',
        x: 49,
        y: 59,
        html: '19<br><span class="suffix">40s</span>',
      },
      {
        id: '1940-title',
        type: 'title',
        x: 49,
        y: 344,
        w: 210,
        html: 'The Beginning',
      },
      {
        id: '1940-rule',
        type: 'rule',
        x: 49,
        y: 398,
        w: 78,
      },
      {
        id: '1940-left-body',
        type: 'body',
        x: 49,
        y: 423,
        w: 200,
        html: 'Started a new division solely managing foreign brand distribution under the name <b>DESIGNER WORLD BRANDS</b> &amp; added more labels like INGERSOLL, INVICTA, and SANTA BARBARA POLO CLUB.',
      },
      {
        id: '1940-portrait',
        type: 'image',
        src: 'x102.png',
        x: 290,
        y: 60,
        w: 330,
        h: 423,
        alt: 'Founder Portrait',
        zIndex: 5,
      },
      {
        id: '1940-label',
        type: 'title',
        x: 611,
        y: 145,
        w: 180,
        isGreen: true,
        html: '1940s',
      },
      {
        id: '1940-right-body',
        type: 'body',
        x: 611,
        y: 228,
        w: 225,
        html: 'Dedicated brand management infrastructure empowered global fashion icons to flourish in the Indian marketplace.',
      },
      {
        id: '1940-store',
        type: 'image',
        src: 'x122.png',
        x: 467,
        y: 350,
        w: 449,
        h: 437,
        alt: 'Nagpal Watch Co. Storefront',
        zIndex: 6,
      },
    ],
  },
  // 1960s
  {
    id: '1960s',
    title: '1960s — The 2nd Generation',
    yStart: 760,
    height: 820,
    elements: [
      {
        id: '1960-label',
        type: 'year-small',
        x: 47,
        y: 218,
        html: '1960s',
      },
      {
        id: '1960-left-body',
        type: 'body',
        x: 47,
        y: 290,
        w: 170,
        html: 'International partnerships formed the backbone of a growing enterprise. By the mid-60s, Nagpals had become a trusted name in the Northern India trade circuit for precision components and watch batteries.',
      },
      {
        id: '1960-family',
        type: 'image',
        src: 'x114.png',
        x: 129,
        y: 429,
        w: 482,
        h: 321,
        alt: '1960s Family Group',
        zIndex: 5,
      },
      {
        id: '1960-year',
        type: 'year-big',
        x: 611,
        y: 53,
        html: '19<br><span class="suffix">60s</span>',
      },
      {
        id: '1960-title',
        type: 'title',
        x: 611,
        y: 359,
        w: 220,
        isGreen: true,
        html: 'The 2nd Generation<br>of Nagpal Watch.CO',
      },
      {
        id: '1960-right-body',
        type: 'body',
        x: 611,
        y: 448,
        w: 245,
        html: 'This was when the 2nd generation of Nagpal’s family entered the business, deepening roots in horology and building relationships with component suppliers across Northern India.',
      },
    ],
  },
  // 1976
  {
    id: '1976',
    title: "1976 — Nagpal's Bombay Was Formed",
    yStart: 1580,
    height: 770,
    elements: [
      {
        id: '1976-year',
        type: 'year-big',
        x: 38,
        y: 126,
        html: '19<br><span class="suffix">76</span>',
      },
      {
        id: '1976-title',
        type: 'title',
        x: 38,
        y: 390,
        w: 220,
        html: '‘Nagpal’s Bombay‘<br>was formed',
      },
      {
        id: '1976-left-body',
        type: 'body',
        x: 38,
        y: 525,
        w: 210,
        html: 'This was when the 2nd generation of Nagpal’s family entered the business, deepening roots in horology and building relationships across Northern India.',
      },
      {
        id: '1976-logo',
        type: 'image',
        src: 'x130.png',
        x: 342,
        y: 254,
        w: 228,
        h: 91,
        alt: "Nagpal's Bombay Logo",
        zIndex: 5,
      },
      {
        id: '1976-label',
        type: 'year-small',
        x: 611,
        y: 160,
        html: '1976',
      },
      {
        id: '1976-right-body',
        type: 'body',
        x: 611,
        y: 239,
        w: 235,
        html: 'This was the time when they travelled to international markets to import parts &amp; components for direct distribution and during various BUTTON CELL brands tied up with NAGPALS BOMBAY for battery distribution all over India. Brands from Japan like MAXELL &amp; Swiss like RENATA became a major area of company’s focus for growth.',
      },
    ],
  },
  // 1991
  {
    id: '1991',
    title: '1991 — A Brand Is Born',
    yStart: 2350,
    height: 670,
    elements: [
      {
        id: '1991-label',
        type: 'year-small',
        x: 38,
        y: 188,
        html: '1991',
      },
      {
        id: '1991-left-body',
        type: 'body',
        x: 38,
        y: 240,
        w: 225,
        html: 'D’SIGNER was not simply a product launch but a philosophical statement. At a time when Indian watchmaking was dominated by mass-market models, D’SIGNER chose craftsmanship over compromise and design over convention.',
      },
      {
        id: '1991-logo',
        type: 'image',
        src: 'x110.png',
        x: 351,
        y: 171,
        w: 211,
        h: 79,
        alt: "D'SIGNER Logo",
        zIndex: 5,
      },
      {
        id: '1991-ad',
        type: 'image',
        src: 'x98.png',
        x: 267,
        y: 302,
        w: 349,
        h: 232,
        alt: "D'SIGNER Couple Advertisement",
        zIndex: 5,
      },
      {
        id: '1991-year',
        type: 'year-big',
        x: 611,
        y: 42,
        html: '19<br><span class="suffix">91</span>',
      },
      {
        id: '1991-title',
        type: 'title',
        x: 611,
        y: 328,
        w: 220,
        isGreen: true,
        html: 'A Brand Is Born',
      },
      {
        id: '1991-right-body',
        type: 'body',
        x: 611,
        y: 370,
        w: 225,
        html: 'D’SIGNER was introduced, a step into creating watches defined by design, quality, and individuality. One of the early Indian brands to design and manufacture to international horological standards.',
      },
    ],
  },
  // 1995
  {
    id: '1995',
    title: '1995 — Style For All',
    yStart: 3020,
    height: 630,
    elements: [
      {
        id: '1995-year',
        type: 'year-big',
        x: 47,
        y: 13,
        html: '19<br><span class="suffix">95</span>',
      },
      {
        id: '1995-title',
        type: 'title',
        x: 47,
        y: 299,
        w: 165,
        html: 'Style For All',
      },
      {
        id: '1995-left-body',
        type: 'body',
        x: 47,
        y: 388,
        w: 210,
        html: 'ESCORT was launched to make timeless design more accessible, bringing style to a wider audience with robust everyday timepieces at honest prices.',
      },
      {
        id: '1995-logo',
        type: 'image',
        src: 'x126.png',
        x: 358,
        y: 97,
        w: 212,
        h: 119,
        alt: 'ESCORT Logo',
        zIndex: 5,
      },
      {
        id: '1995-party',
        type: 'image',
        src: 'x88.png',
        x: 296,
        y: 264,
        w: 407,
        h: 271,
        alt: 'ESCORT Banquet Party',
        zIndex: 5,
      },
      {
        id: '1995-label',
        type: 'year-small',
        x: 609,
        y: 68,
        html: '1995',
      },
      {
        id: '1995-right-body',
        type: 'body',
        x: 609,
        y: 113,
        w: 235,
        html: 'Escort answered a simple question: why shouldn’t every Indian have access to a reliable, beautifully finished timepiece? The market responded with extraordinary enthusiasm.',
      },
    ],
  },
  // 1998
  {
    id: '1998',
    title: '1998 — Introduction of Tissot in India',
    yStart: 3650,
    height: 700,
    elements: [
      {
        id: '1998-label',
        type: 'year-small',
        x: 41,
        y: 123,
        html: '1998',
      },
      {
        id: '1998-left-body',
        type: 'body',
        x: 41,
        y: 205,
        w: 225,
        html: 'Bringing prestige Swiss and French horological brands to Indian retail counters established the Nagpal Group as an esteemed national distributor.',
      },
      {
        id: '1998-meeting',
        type: 'image',
        src: 'x106.png',
        x: 236,
        y: 216,
        w: 393,
        h: 262,
        alt: 'Tissot Launch Meeting',
        zIndex: 5,
      },
      {
        id: '1998-year',
        type: 'year-big',
        x: 616,
        y: 17,
        html: '19<br><span class="suffix">98</span>',
      },
      {
        id: '1998-title',
        type: 'title',
        x: 616,
        y: 349,
        w: 220,
        isGreen: true,
        html: 'Introduction of<br>Tissot in India',
      },
      {
        id: '1998-right-body',
        type: 'body',
        x: 616,
        y: 430,
        w: 226,
        html: 'We were the ones to launch TISSOT watches in India as national distributors. We initiated the distribution for Tissot, Givenchy Paris, Christian Bernard Paris, and Rotary in India.',
      },
    ],
  },
  // 2004
  {
    id: '2004',
    title: "2004 — D'signer Effects",
    yStart: 4350,
    height: 700,
    elements: [
      {
        id: '2004-year',
        type: 'year-big',
        x: 54,
        y: 28,
        html: '20<br><span class="suffix">04</span>',
      },
      {
        id: '2004-title',
        type: 'title',
        x: 54,
        y: 314,
        w: 210,
        html: 'D’signer Effects',
      },
      {
        id: '2004-left-body',
        type: 'body',
        x: 54,
        y: 427,
        w: 230,
        html: 'Connecting brand messaging with high-quality custom corporate gifts allowed businesses across India to elevate their marketing initiatives and employee reward programs.',
      },
      {
        id: '2004-flyer',
        type: 'image',
        src: 'x72.png',
        x: 335,
        y: 191,
        w: 246,
        h: 308,
        alt: "D'SIGNER Effects Flyer",
        zIndex: 5,
      },
      {
        id: '2004-label',
        type: 'year-small',
        x: 616,
        y: 188,
        html: '2004',
      },
      {
        id: '2004-right-body',
        type: 'body',
        x: 616,
        y: 260,
        w: 228,
        html: 'We started a division purely in the corporate gifts &amp; promotion business under the name D’SIGNER EFFECTS. Here the idea was to connect with all small and large organizations, offering all sorts of promotion gifts for schemes and marketing plans.',
      },
    ],
  },
  // 2010
  {
    id: '2010',
    title: '2010 — B2B & Corporate Gifting',
    yStart: 5050,
    height: 900,
    elements: [
      {
        id: '2010-year-left',
        type: 'year-big',
        x: 41,
        y: 146,
        html: '20<br><span class="suffix">10</span>',
      },
      {
        id: '2010-left-body-1',
        type: 'body',
        x: 41,
        y: 225,
        w: 170,
        html: 'DESIGNER WATCHES scaled production skills and managed largest volume B2B orders of watches in lakhs, delivering projects for esteemed groups like TATA INDICOM, REEBOK, NIKON, and PHARMA COMPANIES.',
      },
      {
        id: '2010-left-body-2',
        type: 'body',
        x: 41,
        y: 550,
        w: 175,
        html: 'B2B &amp; Corporate Gifting became a very important focus as wristwatches became a strong category for business promotion and marketing plans for major corporates. Launched clocks &amp; bags category under D’SIGNER for B2B requirements.',
      },
      {
        id: '2010-clock-1',
        type: 'image',
        src: 'x76.png',
        x: 288,
        y: 99,
        w: 164,
        h: 219,
        alt: 'Antique Clock',
        zIndex: 5,
      },
      {
        id: '2010-clock-2',
        type: 'image',
        src: 'x46.png',
        x: 398,
        y: 187,
        w: 245,
        h: 245,
        alt: 'Desk Clock',
        zIndex: 5,
      },
      {
        id: '2010-shelf',
        type: 'image',
        src: 'x50.png',
        x: 197,
        y: 399,
        w: 508,
        h: 339,
        alt: 'Clock Shelves Collection',
        zIndex: 5,
      },
      {
        id: '2010-year-right',
        type: 'year-big',
        x: 616,
        y: 0,
        html: '20<br><span class="suffix">10</span>',
      },
      {
        id: '2010-title',
        type: 'title',
        x: 616,
        y: 302,
        w: 235,
        isGreen: true,
        html: 'B2B &amp; Corporate<br>Gifting',
      },
    ],
  },
  // 2013
  {
    id: '2013',
    title: '2013 — Daniel Klein in India',
    yStart: 5950,
    height: 650,
    elements: [
      {
        id: '2013-year',
        type: 'year-big',
        x: 46,
        y: 1,
        html: '20<br><span class="suffix">13</span>',
      },
      {
        id: '2013-title',
        type: 'title',
        x: 46,
        y: 287,
        w: 225,
        html: 'Daniel Klein in India',
      },
      {
        id: '2013-left-body',
        type: 'body',
        x: 46,
        y: 377,
        w: 210,
        html: 'Got exclusive distribution of Daniel Klein, a leading Turkish brand of watches and fashion accessories, in India.',
      },
      {
        id: '2013-watch',
        type: 'image',
        src: 'x84.png',
        x: 292,
        y: 27,
        w: 347,
        h: 520,
        alt: 'Daniel Klein Watch with Liquid Chrome Splash',
        zIndex: 5,
      },
      {
        id: '2013-label',
        type: 'year-small',
        x: 614,
        y: 96,
        html: '2013',
      },
      {
        id: '2013-right-body',
        type: 'body',
        x: 614,
        y: 220,
        w: 250,
        html: 'Bringing dynamic international styling and accessible luxury to retail counters opened new fashion-forward demographics across all major tier-1 and tier-2 cities.',
      },
    ],
  },
  // 2015
  {
    id: '2015',
    title: '2015 — Beyond Our Own Brand',
    yStart: 6600,
    height: 680,
    elements: [
      {
        id: '2015-label',
        type: 'year-small',
        x: 41,
        y: 157,
        html: '2015',
      },
      {
        id: '2015-left-body',
        type: 'body',
        x: 41,
        y: 430,
        w: 215,
        html: 'Over 500 private labels would trust our manufacturing expertise to engineer precision timepieces adhering to international quality benchmarks.',
      },
      {
        id: '2015-logo',
        type: 'image',
        src: 'x60.png',
        x: 385,
        y: 69,
        w: 150,
        h: 133,
        alt: 'OEM Time Lab Logo',
        zIndex: 5,
      },
      {
        id: '2015-workshop',
        type: 'image',
        src: 'x42.png',
        x: 316,
        y: 219,
        w: 283,
        h: 400,
        alt: 'Every Second Handcrafted Workshop Stack',
        zIndex: 5,
      },
      {
        id: '2015-year',
        type: 'year-big',
        x: 616,
        y: 7,
        html: '20<br><span class="suffix">15</span>',
      },
      {
        id: '2015-title',
        type: 'title',
        x: 616,
        y: 313,
        w: 230,
        isGreen: true,
        html: 'Beyond Our Own<br>Brand',
      },
      {
        id: '2015-right-body',
        type: 'body',
        x: 616,
        y: 405,
        w: 235,
        html: 'Expanding into OEM manufacturing, we began designing and producing watches for global and national brands, marking a significant leap in manufacturing capability.',
      },
    ],
  },
  // 2017
  {
    id: '2017',
    title: '2017 — Adding More Brands',
    yStart: 7280,
    height: 600,
    elements: [
      {
        id: '2017-year',
        type: 'year-big',
        x: 39,
        y: 17,
        html: '20<br><span class="suffix">17</span>',
      },
      {
        id: '2017-title',
        type: 'title',
        x: 39,
        y: 335,
        w: 220,
        html: 'Adding More Brands',
      },
      {
        id: '2017-left-body',
        type: 'body',
        x: 39,
        y: 425,
        w: 230,
        html: 'Same year Designer World stepped into international exports, in London, Singapore, and in Middle Eastern countries like Bahrain and Oman.',
      },
      {
        id: '2017-watch',
        type: 'image',
        src: 'x34.png',
        x: 276,
        y: 307,
        w: 366,
        h: 244,
        alt: 'Mathey-Tissot Chronograph Watch',
        zIndex: 5,
      },
      {
        id: '2017-label',
        type: 'year-small',
        x: 614,
        y: 195,
        html: '2017',
      },
      {
        id: '2017-right-body',
        type: 'body',
        x: 614,
        y: 270,
        w: 238,
        html: 'The house introduced few more international fashion brands in its distribution channel: MATHEY TISSOT and D1 MILANO.',
      },
    ],
  },
  // 2020
  {
    id: '2020',
    title: '2020 — The Digital Shift',
    yStart: 7880,
    height: 500,
    elements: [
      {
        id: '2020-label',
        type: 'year-small',
        x: 50,
        y: 162,
        html: '2020',
      },
      {
        id: '2020-left-body',
        type: 'body',
        x: 50,
        y: 245,
        w: 235,
        html: 'Direct-to-consumer acceleration and modern logistics allowed us to deliver timepieces with agility to watch lovers across India.',
      },
      {
        id: '2020-logo',
        type: 'image',
        src: 'x24.png',
        x: 348,
        y: 261,
        w: 216,
        h: 72,
        alt: 'ghadiwaala Logo',
        zIndex: 5,
      },
      {
        id: '2020-year',
        type: 'year-big',
        x: 625,
        y: 12,
        html: '20<br><span class="suffix">20</span>',
      },
      {
        id: '2020-title',
        type: 'title',
        x: 625,
        y: 318,
        w: 215,
        isGreen: true,
        html: 'The Digital Shift',
      },
      {
        id: '2020-right-body',
        type: 'body',
        x: 625,
        y: 408,
        w: 230,
        html: 'With the rise of e-commerce, we adapted quickly, designing for online-first brands and expanding our reach across digital platforms.',
      },
    ],
  },
  // 2022
  {
    id: '2022',
    title: '2022 — Designer World Brands',
    yStart: 8380,
    height: 600,
    elements: [
      {
        id: '2022-year',
        type: 'year-big',
        x: 50,
        y: 10,
        html: '20<br><span class="suffix">22</span>',
      },
      {
        id: '2022-title',
        type: 'title',
        x: 50,
        y: 305,
        w: 190,
        isGreen: true,
        html: 'Designer World<br>Brands',
      },
      {
        id: '2022-left-body',
        type: 'body',
        x: 50,
        y: 410,
        w: 218,
        html: 'Dedicated brand management infrastructure empowered global fashion icons to flourish in the Indian marketplace.',
      },
      {
        id: '2022-portfolio',
        type: 'image',
        src: 'x20.png',
        x: 129,
        y: 177,
        w: 318,
        h: 212,
        alt: 'Designer World Brands Portfolio',
        zIndex: 5,
      },
      {
        id: '2022-label',
        type: 'title',
        x: 625,
        y: 188,
        w: 230,
        isGreen: true,
        html: '2022',
      },
      {
        id: '2022-right-body',
        type: 'body',
        x: 625,
        y: 268,
        w: 236,
        html: 'Started a new division solely managing foreign brand distribution under the name DESIGNER WORLD BRANDS &amp; added more labels like INGERSOLL, INVICTA, and SANTA BARBARA POLO CLUB.',
      },
    ],
  },
  // 2024
  {
    id: '2024',
    title: "2024 — D'signer Diamond Watches",
    yStart: 8980,
    height: 720,
    elements: [
      {
        id: '2024-label',
        type: 'year-small',
        x: 50,
        y: 151,
        html: '2024',
      },
      {
        id: '2024-left-body',
        type: 'body',
        x: 50,
        y: 248,
        w: 220,
        html: 'Combining modern ethical lab-grown diamonds with Swiss-inspired horology to deliver sophisticated luxury for discerning collectors.',
      },
      {
        id: '2024-watch',
        type: 'image',
        src: 'x16.png',
        x: 253,
        y: 39,
        w: 370,
        h: 463,
        alt: "D'SIGNER Diamond Watches",
        zIndex: 5,
      },
      {
        id: '2024-year',
        type: 'year-big',
        x: 625,
        y: 1,
        html: '20<br><span class="suffix">24</span>',
      },
      {
        id: '2024-title',
        type: 'title',
        x: 625,
        y: 307,
        w: 235,
        isGreen: true,
        html: 'D’signer Diamond<br>Watches',
      },
      {
        id: '2024-right-body',
        type: 'body',
        x: 625,
        y: 417,
        w: 225,
        html: 'Launched Lab Grown Diamond Studded Watches as a new step to reach a more luxury audience, featuring models ranging up to Rs. 1,50,000/-.',
      },
    ],
  },
  // 2025
  {
    id: '2025',
    title: '2025 — Time Corridor',
    yStart: 9700,
    height: 850,
    elements: [
      {
        id: '2025-year',
        type: 'year-big',
        x: 62,
        y: 9,
        html: '20<br><span class="suffix">25</span>',
      },
      {
        id: '2025-title',
        type: 'title',
        x: 62,
        y: 330,
        w: 225,
        html: 'Time Corridor',
      },
      {
        id: '2025-left-body',
        type: 'body',
        x: 62,
        y: 400,
        w: 240,
        html: 'A latest feather in Designer World story. At Designer World it’s not about just the product we make but the aura we pass to our user with the time we design.',
      },
      {
        id: '2025-boutique',
        type: 'image',
        src: 'x12.png',
        x: 290,
        y: 66,
        w: 390,
        h: 585,
        alt: 'Time Corridor Luxury Boutique',
        zIndex: 5,
      },
      {
        id: '2025-label',
        type: 'year-small',
        x: 649,
        y: 158,
        html: '2025',
      },
      {
        id: '2025-right-body',
        type: 'body',
        x: 649,
        y: 290,
        w: 220,
        html: 'This retail Time Boutique is initiated to promote our home brands, D’SIGNER &amp; ESCORT watches at a unique experience store showcasing our prime models, new launches, top sellers &amp; special editions with an appealing display and aura. A gesture to connect &amp; add some value to our happy watch buyers.',
      },
    ],
  },
  // TODAY
  {
    id: 'today',
    title: 'TODAY — Affordable Luxury',
    yStart: 10550,
    height: 640,
    elements: [
      {
        id: 'today-title-left',
        type: 'today',
        x: 38,
        y: 105,
        w: 220,
        html: 'TODAY',
      },
      {
        id: 'today-left-body',
        type: 'body',
        x: 38,
        y: 160,
        w: 220,
        html: 'Blending decades of legacy with modern design, Designer World continues to create watches that balance style, quality, and accessibility.',
      },
      {
        id: 'today-title-right',
        type: 'afford',
        x: 625,
        y: 168,
        w: 220,
        html: 'Affordable Luxury',
      },
      {
        id: 'today-right-body',
        type: 'body',
        x: 625,
        y: 226,
        w: 225,
        html: 'Where heritage meets modern design, Designer World creates watches that combine timeless style, reliable quality, and everyday accessibility.',
      },
      {
        id: 'today-team-photo',
        type: 'image',
        src: 'x8.png',
        x: 155,
        y: 289,
        w: 547,
        h: 365,
        alt: 'Designer World Team Photo',
        zIndex: 5,
      },
    ],
  },
];
