import os
import json
import zipfile
import shutil

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT_DIR = os.path.join(ROOT_DIR, "exported_page_images")
ZIP_OUTPUT = os.path.join(ROOT_DIR, "home2_about5_images.zip")

with open(os.path.join(ROOT_DIR, "media_summary.json"), "r", encoding="utf-8") as f:
    data = json.load(f)

manifest_content = """# Media Asset Manifest: Home-2 & About-5

This package contains all image assets used across the **Home-2** and **About-5** pages, organized into clean folder directories for client handover.

---

## Folder Structure Overview

```
home2_about5_images.zip
├── home-2/                     # Images used on active live /home-2 page (13 images)
├── home-2-all-sections/        # Images from all Home-2 modular sections (25 images)
├── about-5/                    # Images used on /about-5 timeline page (29 images)
└── MANIFEST.md                 # Detailed image usage guide and specifications
```

---

## 1. Home-2 (Active Page Images)

| # | Filename | Original Path | Size | Section / Component Usage |
|---|----------|---------------|------|---------------------------|
"""

for idx, img in enumerate(data["home2_active_images"], 1):
    manifest_content += f"| {idx} | `{img['exported_name']}` | `{img['rel_path']}` | {img['size_kb']} KB | {', '.join(img['used_in'])} |\n"

manifest_content += """
---

## 2. Home-2 (All Section Variants - Extended)

| # | Filename | Original Path | Size | Section / Component Usage |
|---|----------|---------------|------|---------------------------|
"""

for idx, img in enumerate(data["home2_all_images"], 1):
    manifest_content += f"| {idx} | `{img['exported_name']}` | `{img['rel_path']}` | {img['size_kb']} KB | {', '.join(img['used_in'])} |\n"

manifest_content += """
---

## 3. About-5 (Timeline & Heritage Images)

| # | Filename | Original Path | Size | Description / Section |
|---|----------|---------------|------|-----------------------|
"""

for idx, img in enumerate(data["about5_images"], 1):
    manifest_content += f"| {idx} | `{img['exported_name']}` | `{img['rel_path']}` | {img['size_kb']} KB | {', '.join(img['used_in'])} |\n"

manifest_content += """
---

## 4. Video Files Analysis (Home-2)

*Note: Video files are excluded from this image zip to keep the package lightweight, but their details and locations in the project repository are listed below:*

1. **`D_SIGNER shot video 01.mp4`** (12.22 MB)  
   - Path: `/public/images/new-img/video/D_SIGNER shot video 01.mp4`  
   - Usage: Primary luxury video hero background in `HeroBanner.tsx` & `FullVideoBanner.tsx`
2. **`video-transfer.mp4`** (7.36 MB)  
   - Path: `/public/images/new-img/video-transfer.mp4`  
   - Usage: 3D watch rotating interactive anatomy showcase in `WatchDetails.tsx`
3. **`video-transfer-alpha.webm`** (7.43 MB)  
   - Path: `/public/images/new-img/video-transfer-alpha.webm`  
   - Usage: Transparent WebM alpha video for 3D watch anatomy in `WatchDetails.tsx`
4. **`banner-34.mp4`** (7.02 MB)  
   - Path: `/public/img/banner-34.mp4`  
   - Usage: Secondary fallback video in `HeroBanner.tsx`
5. **`videobanner-1.mp4`** (91.08 MB)  
   - Path: `/public/images/new-content/videobanner-1.mp4`  
   - Usage: High-resolution full video banner in `HeroSection.tsx`

---
*Generated by Antigravity IDE Automation for Client Handover.*
"""

# Write MANIFEST.md in EXPORT_DIR and workspace root
with open(os.path.join(EXPORT_DIR, "MANIFEST.md"), "w", encoding="utf-8") as f:
    f.write(manifest_content)

with open(os.path.join(ROOT_DIR, "PAGE_IMAGES_MANIFEST.md"), "w", encoding="utf-8") as f:
    f.write(manifest_content)

# Re-zip with manifest included
if os.path.exists(ZIP_OUTPUT):
    os.remove(ZIP_OUTPUT)

with zipfile.ZipFile(ZIP_OUTPUT, 'w', zipfile.ZIP_DEFLATED) as zf:
    for root, dirs, files in os.walk(EXPORT_DIR):
        for file in sorted(files):
            abs_f = os.path.join(root, file)
            rel_z = os.path.relpath(abs_f, EXPORT_DIR)
            zf.write(abs_f, rel_z)

zip_size_mb = os.path.getsize(ZIP_OUTPUT) / (1024.0 * 1024.0)
print(f"Re-created zip with MANIFEST.md: {ZIP_OUTPUT} ({round(zip_size_mb, 2)} MB)")
